version: '3.8'
services:
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.30.4
    ports:
    - 8080:8080
    - 50051:50051 # gRPC
    restart: on-failure
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      ENABLE_MODULES: ''
      CLUSTER_HOSTNAME: 'node1'
      AUTHORIZATION_TYPE: 'none'  # Explicitly disable authentication
      # Single node mode
      RAFT_BOOTSTRAP_EXPECT: 1
    volumes:
      - ./weaviate_data:/var/lib/weaviate
    hostname: node1